### ISSUE TITLE
Problem with new taxonomies and css overlaping divs

### ISSUE THREAD

**Issue by ImAlexisSaez** [appernetic/hugo-nederburg-theme#23]
Hi,

Source repository: https://github.com/ImAlexisSaez/infinitoscontrastes
Live version: https://imalexissaez.github.io/

I created a new taxonomy, projects, and modified the template "single.html" to see the three taxonomies of a post (categories, tags and projects). For that, I defined a new css class, entry-projects, and modified a little bit the css file.

However, if I uncomment the first line in this block of code

```css
/*.entry-meta-bottom.float .entry-projects,*/
  .entry-meta-bottom.float .entry-tags,
  .entry-meta-bottom.float .entry-categories {
    position: absolute;
    width: 16.66%;
    left: 0;
    top: 4.5em;
    text-align: right;
    padding-left: 5.55%;
  }
```

the `div` of the project overlaps the `div` of the categories (in desktop resolutions). I don't know why doesn't add a `style="top ---px;"` to the div of the project. In mobile resolutions works as intended.

Thank you.
