### ISSUE TITLE
"map[]" above every post tile

### ISSUE THREAD

**Issue by pks111607** [appernetic/hugo-nederburg-theme#38]
On the homepage there is the following text shown above every post tile:
```
map[]
<post>

map[]
<post>
...
```

This occurs with the latest version of the theme. Is there something I am doing wrong?

**Comment by pks111607** [comment]
Did some further investigation. Turns out it is mandatory to have the ```[params.writers."Some Writer"]``` parameter in the configuration. My workaround for now is to set a dummy writer:

```toml
  [params.writers]
    [params.writers."Another Author"]
      link = "https://www.anotherauthor.com"
      email = "anotherauthor@email.com"
      bio = [
        "Another author is a something</a>. This is the author bio shown after posts."
      ]
      facebook      = "full profile url in facebook"
      googleplus    = "full profile url in googleplus"
      twitter       = "full profile url in twitter"
      linkedin      = "full profile url in linkedin"
      stackoverflow = "full profile url in stackoverflow"
      instagram     = "full profile url in instagram"
      github        = "full profile url in github"
      pinterest     = "full profile url in pinterest"
```

Would it be possible to either make this a little clearer in the documentation, or change so that the ```params.writers.*``` is not necessary for the homepage to load correctly?
